markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - index.md
  - number.md
  - create.md
  - optional_zero.md
  - Bases:
      - base2.md
      - base3.md
      - base26c.md

site_name: RebelBase
site_url: https://rebelbase.dev/

theme:
  name: material
