markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - index.md
  - number.md
  - create.md
  - optional-zero.md
  - bases.md

site_name: RebelBase
site_url: https://rebelbase.dev/

theme:
  name: material
