markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - index.md
  - number.md
  - create.md
  - optional_zero.md

site_name: RebelBase
site_url: https://cariad.github.io/rebelbase/

theme:
  name: material
