name: push
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Validate
        uses: devcontainers/ci@v0.2
        with:
          push: never
          runCmd: >
            pip install --upgrade --user -r requirements.dev.txt &&
            ./validate.sh &&
            coverage xml &&
            ./build.sh ${{ github.ref_name }}

      - name: Publish code coverage
        uses: codecov/codecov-action@v3.1.1
